imports:
    - { resource: view.yml }

parameters:
    support_tools.info_collector.registry.class: EzSystems\EzSupportToolsBundle\SystemInfo\Registry\IdentifierBased
    support_tools.info_collectors.composer.lock_file.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\JsonComposerLockSystemInfoCollector
    support_tools.info_collectors.database.doctrine.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\DoctrineDatabaseSystemInfoCollector
    support_tools.info_collectors.hardware.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcHardwareSystemInfoCollector
    support_tools.info_collectors.php.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcPhpSystemInfoCollector
    support_tools.info_collectors.symfony.kernel.config.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\ConfigurationSymfonyKernelSystemInfoCollector

services:
    support_tools.info_collector.registry:
        class: %support_tools.info_collector.registry.class%

    support_tools.info_collector.system_info.ezc:
        class: ezcSystemInfo
        factory: [EzSystems\EzSupportToolsBundle\SystemInfo\EzcSystemInfoFactory, buildEzcSystemInfo]

    support_tools.info_collectors.composer.lock_file:
        class: %support_tools.info_collectors.composer.lock_file.class%
        arguments:
            - "%kernel.root_dir%/../composer.lock"
        tags:
            - { name: "support_tools.info_collector", alias: "composer" }

    support_tools.info_collectors.database.doctrine:
        class: %support_tools.info_collectors.database.doctrine.class%
        arguments:
            - @database_connection
        tags:
            - { name: "support_tools.info_collector", alias: "database" }

    support_tools.info_collectors.hardware.ezc:
        class: %support_tools.info_collectors.hardware.ezc.class%
        arguments:
            - @support_tools.info_collector.system_info.ezc
        tags:
            - { name: "support_tools.info_collector", alias: "hardware" }

    support_tools.info_collectors.php.ezc:
        class: %support_tools.info_collectors.php.ezc.class%
        arguments:
            - @support_tools.info_collector.system_info.ezc
        tags:
            - { name: "support_tools.info_collector", alias: "php" }

    support_tools.info_collectors.symfony.kernel.config:
        class: %support_tools.info_collectors.symfony.kernel.config.class%
        arguments:
            - @kernel
            - %kernel.bundles%
        tags:
            - { name: "support_tools.info_collector", alias: "symfony_kernel" }
