imports:
    - { resource: view.yml }

parameters:
    support_tools.info_collectors.database.doctrine.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\DoctrineDatabaseSystemInfoCollector
    support_tools.info_collectors.hardware.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcHardwareSystemInfoCollector
    support_tools.info_collectors.php.ezc.class: EzSystems\EzSupportToolsBundle\SystemInfo\Collector\EzcPhpSystemInfoCollector

services:
    support_tools.info_collector.system_info.ezc:
        class: ezcSystemInfo
        factory: [EzSystems\EzSupportToolsBundle\SystemInfo\EzcSystemInfoFactory, buildEzcSystemInfo]

    support_tools.info_collectors.database.doctrine:
        class: %support_tools.info_collectors.database.doctrine.class%
        arguments:
            - @database_connection

    support_tools.info_collectors.hardware.ezc:
        class: %support_tools.info_collectors.hardware.ezc.class%
        arguments:
            - @support_tools.info_collector.system_info.ezc

    support_tools.info_collectors.php.ezc:
        class: %support_tools.info_collectors.php.ezc.class%
        arguments:
            - @support_tools.info_collector.system_info.ezc
